#ifndef BSP_BOARD_PINS_H
#define BSP_BOARD_PINS_H

#include "bsp/stm32f103_regs.h"

/* GPIOA_CRL 中每个引脚占 4 bit：低 2 位 MODE，高 2 位 CNF */
#define BOARD_GPIO_CRL_PIN_FIELD_MASK   (0xFU)

/* PA0 = TIM2_CH1（复用推挽输出1011） */
#define BOARD_GPIO_PA0_CRL_POS          (0U)
#define BOARD_GPIO_PA0_CRL_MASK         (BOARD_GPIO_CRL_PIN_FIELD_MASK << BOARD_GPIO_PA0_CRL_POS)
#define BOARD_GPIO_PA0_AF_PP_50MHZ      (0xBU << BOARD_GPIO_PA0_CRL_POS)

/* GPIOA_CRH 中每个引脚占 4 bit：CNF[1:0] + MODE[1:0] */
#define BOARD_GPIO_CRH_PIN_FIELD_MASK   (0xFU)

/* PA9 = USART1_TX */
#define BOARD_GPIO_PA9_CRH_POS          (4U)
#define BOARD_GPIO_PA9_CRH_MASK         (BOARD_GPIO_CRH_PIN_FIELD_MASK << BOARD_GPIO_PA9_CRH_POS)
#define BOARD_GPIO_PA9_AF_PP_50MHZ      (0xBU << BOARD_GPIO_PA9_CRH_POS)

/* PA10 = USART1_RX */
#define BOARD_GPIO_PA10_CRH_POS         (8U)
#define BOARD_GPIO_PA10_CRH_MASK        (BOARD_GPIO_CRH_PIN_FIELD_MASK << BOARD_GPIO_PA10_CRH_POS)
#define BOARD_GPIO_PA10_INPUT_FLOATING  (0x4U << BOARD_GPIO_PA10_CRH_POS)

#define BOARD_USART1_GPIO_CRH_REG       GPIOA_CRH

#endif
