#ifndef BSP_BOARD_PINS_H
#define BSP_BOARD_PINS_H

#include "bsp/stm32f103_regs.h"

/*
 * GPIO 配置寄存器中每个引脚占 4 bit：低 2 位 MODE，高 2 位 CNF。
 * 不同引脚通过位偏移定位：CRL 管理 PA0..PA7，CRH 管理 PA8..PA15。
 */
#define BOARD_GPIO_CRL_PIN_FIELD_MASK   (0xFU)
#define BOARD_GPIO_CRH_PIN_FIELD_MASK   (0xFU)

/* PA1 = ADC1_IN1（光敏模块模拟电压；模拟输入 CNF=00 MODE=00 -> 0x0） */
#define BOARD_GPIO_PA1_CRL_POS          (4U)
#define BOARD_GPIO_PA1_CRL_MASK         (BOARD_GPIO_CRL_PIN_FIELD_MASK << BOARD_GPIO_PA1_CRL_POS)
#define BOARD_GPIO_PA1_ANALOG           (0x0U << BOARD_GPIO_PA1_CRL_POS)

/* PA0 = TIM2_CH1（复用推挽输出 50MHz，CNF=10、MODE=11 -> 0xB） */
#define BOARD_GPIO_PA0_CRL_POS          (0U)
#define BOARD_GPIO_PA0_CRL_MASK         (BOARD_GPIO_CRL_PIN_FIELD_MASK << BOARD_GPIO_PA0_CRL_POS)
#define BOARD_GPIO_PA0_AF_PP_50MHZ      (0xBU << BOARD_GPIO_PA0_CRL_POS)

/* PA9 = USART1_TX（复用推挽输出 50MHz） */
#define BOARD_GPIO_PA9_CRH_POS          (4U)
#define BOARD_GPIO_PA9_CRH_MASK         (BOARD_GPIO_CRH_PIN_FIELD_MASK << BOARD_GPIO_PA9_CRH_POS)
#define BOARD_GPIO_PA9_AF_PP_50MHZ      (0xBU << BOARD_GPIO_PA9_CRH_POS)

/* PA10 = USART1_RX（浮空输入，CNF=01、MODE=00 -> 0x4） */
#define BOARD_GPIO_PA10_CRH_POS         (8U)
#define BOARD_GPIO_PA10_CRH_MASK        (BOARD_GPIO_CRH_PIN_FIELD_MASK << BOARD_GPIO_PA10_CRH_POS)
#define BOARD_GPIO_PA10_INPUT_FLOATING  (0x4U << BOARD_GPIO_PA10_CRH_POS)

#define BOARD_USART1_GPIO_CRH_REG       GPIOA_CRH

/* PB8/PB9 = I2C1_SCL/I2C1_SDA（重映射后；复用开漏输出 50MHz，CNF=11、MODE=11 -> 0xF）。
 * PB8 占 CRH[3:0]，PB9 占 CRH[7:4]，所以两个引脚组合掩码是 0x000000FF。 */
#define BOARD_GPIO_PB8_PB9_CRH_MASK     (0x000000FFUL)
#define BOARD_GPIO_PB8_PB9_AF_OD_50MHZ  (0x000000FFUL)

/* PA6/PA7 = TIM3_CH1/CH2（编码器 A/B 输入；带上拉浮空也能用，但带上拉更抗噪）。
 *   CNF=10（输入带上拉/下拉），MODE=00（输入）-> 4 bit 值 0x8。
 *   ODR.PA6=1, ODR.PA7=1 才是上拉（写 GPIOA_ODR 完成）。
 *   PA6 占 CRL[27:24]，PA7 占 CRL[31:28]。 */
#define BOARD_GPIO_PA6_CRL_POS          (24U)
#define BOARD_GPIO_PA6_CRL_MASK         (BOARD_GPIO_CRL_PIN_FIELD_MASK << BOARD_GPIO_PA6_CRL_POS)
#define BOARD_GPIO_PA6_INPUT_PULL       (0x8U << BOARD_GPIO_PA6_CRL_POS)

#define BOARD_GPIO_PA7_CRL_POS          (28U)
#define BOARD_GPIO_PA7_CRL_MASK         (BOARD_GPIO_CRL_PIN_FIELD_MASK << BOARD_GPIO_PA7_CRL_POS)
#define BOARD_GPIO_PA7_INPUT_PULL       (0x8U << BOARD_GPIO_PA7_CRL_POS)

#define BOARD_GPIO_PA6_PA7_ODR_PULLUP   ((1U << 6) | (1U << 7))

#endif
