#ifndef STM32_INCLUDE_RCC_H
#define STM32_INCLUDE_RCC_H

#include "bsp/stm32f103_regs.h"

/* USART1 所需 APB2 时钟位：AFIO + GPIOA + USART1 */
#define RCC_APB2_USART1_REQUIRED_BITS  (RCC_AFIOEN_BIT | RCC_IOPAEN_BIT | RCC_USART1EN_BIT)

#endif /* STM32_INCLUDE_RCC_H */